---
- name: DBserver setup  
  hosts: dbservers
  become: yes
    # vars: 
    #dbname: eletric
    #dbuser: current
    #dbpass: tesla  
  
  tasks:
    - debug:
        msg: "The dbname is {{dbname}}"   
    - name: Install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present
    - name: start mariadb-server
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
    - name: Install PyMySQL
      ansible.builtin.yum:
         name: python3-PyMySQL
         state: present      
 
    - name: Create a new database with name 'account'
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present 
        login_unix_socket: /var/lib/mysql/mysql.sock     

    - name: Create database user with name 'vprofile'
      community.mysql.mysql_user:
         name: "{{dbuser}}"
         password: "{{dbpass}}"
         priv: '*.*:ALL'
         state: present   
         login_unix_socket: /var/lib/mysql/mysql.sock 
      vars:
        column_case_sensitive: false      
